disqus:
  comments: true
  disqus_shortname: millennial-3
google-ID: UA-156361432-1
menu:
  - name: Geopolitics
    folder: pages
    file: geopolitics.html
  - name: Culture
    folder: pages
    file: culture.html
  - name: Music
    folder: pages
    file: music.html
  - name: Tech
    folder: pages
    file: tech.html
  - name: Sex
    folder: pages
    file: sex.html
  - name: Drugs
    folder: pages
    file: drugs.html
  - name: Experiments
    folder: pages
    file: experiments.html
social:
  - icon: twitter
    link: 'https://twitter.com/TheDistinctor'
  - icon: facebook
    link: 'https://www.facebook.com/thedistinctor'
  - icon: instagram
    link: 'https://www.instagram.com/the_distinctor/'
  - icon: envelope
    link: 'heron.qudsi@gmail.com'
  - icon: rss-square
    link: feed.xml
pagination:
  next_page: Newer
  previous_page: Older
sharing_button_prompt: Feel free to share!
related_posts:
post_date_prefix: Written on
