disqus:
  comments: false
  disqus_shortname: millennial-3
google-ID: UA-112060364-2
menu:
  - name: Geopolitics
    folder: pages
    file: geopolitics.html
  - name: Culture
    folder: pages
    file: resources.html
  - name: Music
    folder: pages
    file: sample-posts.html
  - name: Tech
    folder: pages
    file: documentation.html
  - name: Sex
    folder: pages
    file: about.html
  - name: Drugs
    folder: pages
    file: contact.html
  - name: Experiments
    folder: pages
    file: experiments.html
social:
  - icon: twitter
    link: '#'
  - icon: facebook
    link: '#'
  - icon: instagram
    link: '#'
  - icon: envelope
    link: '#'
  - icon: rss-square
    link: feed.xml
pagination:
  next_page: Newer
  previous_page: Older
sharing_button_prompt: Feel free to share!
related_posts:
post_date_prefix: Written on